[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "theroadragetrip"
version = "0.6.0beta"
description = "PoC top-down driving game using OSM data"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pygame",
    "requests",
    "pyproj",
]

[tool.setuptools.package-data]
theroadragetrip = ["assets/*", "sounds/*", "sounds/passenger_chatter/*.wav"]
