"""The Road Rage Trip package.

A PoC top-down driving game using real-world OSM data for procedural environments.
"""

from .geo import clamp, compute_bbox, dist_point_to_segment, meters_to_latlon, point_in_polygon
from .main import BBOX, main
from .osm import (
    BBOX_PRESETS,
    CITY_CENTERS,
    DEFAULT_BBOX,
    DEFAULT_OVERPASS_ENDPOINTS,
    DEFAULT_ROAD_HALF_WIDTH_M,
    DEFAULT_SPEED_LIMITS_KMH,
    HIGHWAY_HALF_WIDTH,
    AutoFetchManager,
    Building,
    Crossing,
    Place,
    Scenery,
    TaxiStop,
    TrafficLight,
    Water,
    Way,
    bbox_from_center,
    build_ways,
    fetch_osm_ways,
    load_local_sample,
    load_osm_cache,
    save_osm_cache,
)
from .physics import (
    ACCEL,
    BRAKE,
    FRICTION,
    MAX_SPEED,
    STEER_RATE,
    STEER_SPEED_FACTOR,
    Car,
    SpatialWayGrid,
    is_car_road,
    is_on_road,
    is_point_in_water,
    is_point_on_road,
    get_current_road_at_car,
    reset_trip,
    respawn_car,
    update_car_physics,
)
from .render import (
    FPS,
    PX_PER_M,
    SCREEN_H,
    SCREEN_W,
    draw_buildings,
    draw_car,
    draw_city_selection_menu,
    draw_compass,
    draw_crossings,
    draw_hud,
    draw_labels,
    draw_loading_screen,
    draw_npc_cars,
    draw_pause_menu,
    draw_pedestrians,
    draw_scenery,
    draw_traffic_lights,
    draw_waters,
    draw_ways,
    get_viewport_bounds,
    world_to_screen,
)
from .traffic import NPCCar, TrafficManager

__all__ = [
    # Geo
    "clamp",
    "compute_bbox",
    "dist_point_to_segment",
    "point_in_polygon",
    "meters_to_latlon",
    # OSM
    "BBOX",
    "BBOX_PRESETS",
    "CITY_CENTERS",
    "DEFAULT_BBOX",
    "DEFAULT_OVERPASS_ENDPOINTS",
    "DEFAULT_ROAD_HALF_WIDTH_M",
    "DEFAULT_SPEED_LIMITS_KMH",
    "HIGHWAY_HALF_WIDTH",
    "bbox_from_center",
    "Way",
    "Water",
    "Building",
    "Scenery",
    "TaxiStop",
    "Place",
    "TrafficLight",
    "Crossing",
    "load_local_sample",
    "load_osm_cache",
    "save_osm_cache",
    "fetch_osm_ways",
    "build_ways",
    "AutoFetchManager",
    # Physics
    "Car",
    "ACCEL",
    "BRAKE",
    "FRICTION",
    "STEER_RATE",
    "STEER_SPEED_FACTOR",
    "MAX_SPEED",
    "SpatialWayGrid",
    "is_car_road",
    "is_on_road",
    "is_point_on_road",
    "is_point_in_water",
    "get_current_road_at_car",
    "reset_trip",
    "respawn_car",
    "update_car_physics",
    # Traffic
    "NPCCar",
    "TrafficManager",
    # Render
    "SCREEN_W",
    "SCREEN_H",
    "FPS",
    "PX_PER_M",
    "world_to_screen",
    "get_viewport_bounds",
    "draw_scenery",
    "draw_waters",
    "draw_buildings",
    "draw_ways",
    "draw_crossings",
    "draw_traffic_lights",
    "draw_npc_cars",
    "draw_car",
    "draw_compass",
    "draw_hud",
    "draw_labels",
    "draw_loading_screen",
    "draw_city_selection_menu",
    "draw_pause_menu",
    # Main
    "main",
]


