"""Small built-in Finnish and English translation table."""

SUPPORTED_LANGUAGES = ("fi", "en")
LANGUAGE_NAMES = {"fi": "Suomi", "en": "English"}

TRANSLATIONS = {
    "fi": {
        "select_language": "Valitse kieli",
        "language_hint": "Vasen/Oikea tai numeronäppäin, ENTER / SPACE vahvistaa",
        "select_city": "Valitse aloituskaupunki (4x4 km OSM-kartta)",
        "city_hint": "UP/DOWN/LEFT/RIGHT tai 1-0, ENTER / SPACE aloittaa, ESC lopettaa",
        "refresh_map": "Hae uusin kartta",
        "settings": "ASETUKSET",
        "language": "Kieli",
        "master_volume": "Kokonaisäänenvoimakkuus",
        "music_volume": "Taustaääni",
        "effects_volume": "Tehosteet",
        "overpass_endpoints": "Overpass-palvelimet",
        "settings_hint": "UP/DOWN valitsee | LEFT/RIGHT säätää | endpoint-kohdassa kirjoita | ESC takaisin",
        "paused": "PELI TAUKOLLA",
        "continue": "Jatka peliä",
        "help": "Ohjeet ja pelin idea",
        "settings_menu": "Asetukset",
        "change_city": "Vaihda kaupunkia",
        "main_menu": "Alkuvalikko",
        "exit": "Lopeta peli",
        "help_close": "Esc / F1: sulje",
        "phone": "Puhelin: tarjoukset",
        "select_ride": "Valitse kyyti puhelimessa",
        "rage": "Raivohuuto",
        "respawn": "Respawn",
        "cancel_ride": "Hylkää kyyti",
        "reset_trip": "Nollaa matkamittari",
        "labels": "Nimet päälle / pois",
        "lane_assist": "Kaista-avustin",
        "speed_limiter": "Nopeusrajoitin",
        "red_assist": "Liikennevaloavustin",
        "zoom": "Zoomaus",
        "compass": "Kompassi",
        "pause": "Tauko",
        "help_short": "Avaa nämä ohjeet",
        "screenshot": "Tallenna kuvakaappaus",
        "on": "PÄÄLLÄ",
        "off": "POIS",
        "controls": "Ohjaus",
        "ways": "Tiet",
        "zoom_level": "Zoomaus",
        "latitude": "Lat",
        "longitude": "Lon",
        "lane_assist_active": "Kaista-avustin",
        "client": "asiakas",
        "points": "pistettä",
        "loading_scenery": "Ladataan maisemaa...",
        "loading_osm": "Ladataan OpenStreetMap-teitä ja maisemaa...",
        "ready": "Valmis",
        "select_mode": "Valitse pelimoodi",
        "career": "Ura",
        "gig_driver": "Keikkakuski",
        "reset_career": "Nollaa ura",
        "clear_cache": "Tyhjennä välimuisti kokonaan",
        "exit_car": "Poistu autosta / palaa autoon",
        "walk": "Kävele",
        "run": "Juokse",
        "career_city": "Uran kaupunki",
        "career_complete": "Ura suoritettu! Helsinki on valloitettu.",
        "city_summary": "Kaupungin yhteenveto",
        "city_summary_score": "Pisteet: {score}",
        "city_summary_fares": "Ajetut keikat: {fares}",
        "next_city": "Seuraava kaupunki: {city}",
        "continue_enter": "Paina Enter jatkaaksesi",
        "career_total_score": "Uran kokonaispisteet: {score}",
        "select_choose_resume": "Ylös/alas = valitse | Enter/Space = vahvista | Esc = jatka",
        "taxi_phone": "TAKSIPUHELIN",
        "pickup_short": "NOUTO",
        "dropoff_short": "PERILLE",
        "fare_pickup": "KYYTI: Nouda {name} paikasta {address}",
        "fare_dropoff": "KYYTI: Vie {name} määränpäähän {address}",
        "time_left": "aikaa",
        "speed_camera_hit": "Peltikamera! -{penalty} pistettä",
        "police_stop": "Poliisipysäytys! -{penalty} pistettä",
        "crash": "Kolari! -{penalty} pistettä",
        "building_crash": "Törmäys rakennukseen! -{penalty} pistettä",
        "tree_crash": "Törmäys puuhun! -{penalty} pistettä",
        "red_light_violation": "Punaisen valon rikkomus! -{penalty} pistettä",
        "wrong_way_penalty": "Väärään suuntaan! -{penalty} pistettä",
        "new_fare_at": "Uusi kyyti! Nouda {name} paikasta {address}",
        "slow_pickup_notice": "Hidasta noutaaksesi asiakkaan!",
        "slow_dropoff_notice": "Hidasta pysähtyäksesi määränpäähän!",
        "idea": "Pelin idea",
        "story": "Taustatarina",
        "drive": "Kiihdytä",
        "brake": "Jarruta / peruuta",
        "left": "Ohjaa vasemmalle",
        "right": "Ohjaa oikealle",
        "open_phone": "Avaa puhelin (P) ja valitse kyyti aloittaaksesi.",
        "finish_or_cancel": "Viimeistele tai peruuta nykyinen kyyti ensin",
        "no_requests": "Ei tarjouksia saatavilla",
        "pickup": "Nouto",
        "to": "Määränpää",
        "distance_client": "Matka asiakkaalle",
        "close_phone": "P / Esc: sulje",
        "reject_phone": "X: hylkää kyyti",
        "new_request": "Uusi kyyti odottaa puhelimessa.",
        "phone_available": "UUSI KYYTI! Avaa puhelin (P)",
        "stand_boarded": "{name} hyppäsi kyytiin! Määränpää: {address}",
        "hail_boarded": "{name} huusi taksin! Määränpää: {address}",
        "hail_walking": "{name} huusi taksin ja kävelee taksiin...",
        "slow_pickup": "Hidasta noutaaksesi asiakkaan!",
        "walking": "kävelee taksiin...",
        "boarded": "nousi kyytiin! Määränpää",
        "slow_dropoff": "Hidasta pysähtyäksesi määränpäähän!",
        "fare_complete": "Kyyti valmis!",
        "road": "Tie", "off_road": "Maastossa", "limit": "Rajoitus",
        "trip": "Matka", "odometer": "Mittari", "trip_meter": "Trippimittari", "career_meter": "Matkamittari", "score": "PISTEET",
        "fares": "Kyydit", "speed": "NOPEUS", "rage_meter": "RAIVO",
        "walking_named": "{name} kävelee taksiin...",
        "boarded_destination": "{name} nousi kyytiin! Määränpää: {address}",
        "fare_complete_points": "Kyyti valmis! +{earned} pistettä ({avg:.0f} km/h keskiarvo, {seconds:.1f} s)",
    },
    "en": {
        "select_language": "Select language",
        "language_hint": "LEFT/RIGHT or number key, ENTER / SPACE confirms",
        "select_city": "Select starting city (4x4 km OSM map)",
        "city_hint": "UP/DOWN/LEFT/RIGHT or 1-0, ENTER / SPACE starts, ESC quits",
        "refresh_map": "Fetch latest map",
        "settings": "SETTINGS",
        "language": "Language",
        "master_volume": "Master volume",
        "music_volume": "Background sound",
        "effects_volume": "Sound effects",
        "overpass_endpoints": "Overpass endpoints",
        "settings_hint": "UP/DOWN selects | LEFT/RIGHT adjusts | type in endpoint field | ESC back",
        "paused": "GAME PAUSED",
        "continue": "Continue Game",
        "help": "Controls & Objective",
        "settings_menu": "Settings",
        "change_city": "Change City",
        "main_menu": "Main Menu",
        "exit": "Exit Game",
        "help_close": "Esc / F1: close",
        "phone": "Phone: ride offers",
        "select_ride": "Select a ride in the phone",
        "rage": "Rage shout",
        "respawn": "Respawn",
        "cancel_ride": "Cancel fare",
        "reset_trip": "Reset trip meter",
        "labels": "Toggle labels",
        "lane_assist": "Lane assist",
        "speed_limiter": "Speed limiter",
        "red_assist": "Traffic light assist",
        "zoom": "Zoom",
        "compass": "Compass",
        "pause": "Pause",
        "help_short": "Open these instructions",
        "screenshot": "Save screenshot",
        "on": "ON",
        "off": "OFF",
        "controls": "Controls",
        "ways": "Ways",
        "zoom_level": "Zoom",
        "latitude": "Lat",
        "longitude": "Lon",
        "lane_assist_active": "Lane Assist",
        "client": "client",
        "points": "pts",
        "loading_scenery": "Loading scenery...",
        "loading_osm": "Loading OpenStreetMap roads & scenery...",
        "ready": "Ready",
        "select_mode": "Select game mode",
        "career": "Career",
        "gig_driver": "Gig Driver",
        "reset_career": "Reset career",
        "clear_cache": "Clear all map cache",
        "exit_car": "Exit / enter taxi",
        "walk": "Walk",
        "run": "Run",
        "career_city": "Career city",
        "career_complete": "Career complete! Helsinki conquered.",
        "city_summary": "City summary",
        "city_summary_score": "Score: {score}",
        "city_summary_fares": "Fares completed: {fares}",
        "next_city": "Next city: {city}",
        "continue_enter": "Press Enter to continue",
        "career_total_score": "Total career score: {score}",
        "select_choose_resume": "UP/DOWN = select | ENTER/SPACE = choose | ESC = resume",
        "taxi_phone": "TAXI PHONE",
        "pickup_short": "PICKUP",
        "dropoff_short": "DROPOFF",
        "fare_pickup": "FARE: Pick up {name} at {address}",
        "fare_dropoff": "FARE: Take {name} to {address}",
        "time_left": "Time",
        "speed_camera_hit": "Speed camera! -{penalty} pts",
        "police_stop": "Police stop! -{penalty} pts",
        "crash": "Crash! -{penalty} pts",
        "building_crash": "Building crash! -{penalty} pts",
        "tree_crash": "Tree crash! -{penalty} pts",
        "red_light_violation": "Red Light Violation! -{penalty} pts",
        "wrong_way_penalty": "Wrong Way Penalty! -{penalty} pts",
        "new_fare_at": "New fare! Pick up {name} at {address}",
        "slow_pickup_notice": "Slow down to pick up passenger!",
        "slow_dropoff_notice": "Slow down at destination to drop off!",
        "idea": "Game objective",
        "story": "Background story",
        "drive": "Accelerate",
        "brake": "Brake / reverse",
        "left": "Steer left",
        "right": "Steer right",
        "open_phone": "Press P to open the phone and choose a ride.",
        "finish_or_cancel": "Finish or cancel the current fare first",
        "no_requests": "No requests available",
        "pickup": "Pickup",
        "to": "Destination",
        "distance_client": "Distance to client",
        "close_phone": "P / Esc: close",
        "reject_phone": "X: reject ride",
        "new_request": "A new ride is waiting in the phone.",
        "phone_available": "NEW RIDE! Open phone (P)",
        "stand_boarded": "{name} jumped in! Destination: {address}",
        "hail_boarded": "{name} hailed your taxi! Destination: {address}",
        "hail_walking": "{name} hailed your taxi and is walking over...",
        "slow_pickup": "Slow down to pick up passenger!",
        "walking": "is walking to the taxi...",
        "boarded": "boarded! Destination",
        "slow_dropoff": "Slow down at destination to drop off!",
        "fare_complete": "Fare complete!",
        "road": "Road", "off_road": "Off-road", "limit": "Limit",
        "trip": "Trip", "odometer": "Odo", "trip_meter": "Trip meter", "career_meter": "Odometer", "score": "SCORE",
        "fares": "Fares", "speed": "SPEED", "rage_meter": "RAGE",
        "walking_named": "{name} is walking to the taxi...",
        "boarded_destination": "{name} boarded! Destination: {address}",
        "fare_complete_points": "Fare complete! +{earned} pts ({avg:.0f} km/h average in {seconds:.1f}s)",
    },
}


def normalize_language(language: str) -> str:
    return language if language in SUPPORTED_LANGUAGES else "fi"


def tr(language: str, key: str, **values: object) -> str:
    text = TRANSLATIONS[normalize_language(language)].get(key, key)
    return text.format(**values) if values else text
