"""Small built-in Finnish and English translation table."""

SUPPORTED_LANGUAGES = ("fi", "en")
LANGUAGE_NAMES = {"fi": "Suomi", "en": "English"}

TRANSLATIONS = {
    "fi": {
        "select_language": "Valitse kieli",
        "language_hint": "Vasen/Oikea tai numeronäppäin, ENTER / SPACE vahvistaa",
        "select_city": "Valitse aloituskaupunki (3x3 km OSM-kartta)",
        "city_hint": "NUOLET tai 1-0/A-D/G-Z valitsee, E muokkaa, F hakee kartan, ENTER / SPACE aloittaa, ESC lopettaa",
        "refresh_map": "Hae uusin kartta",
        "edit_city_list": "Muokkaa kaupunkilistaa",
        "settings": "ASETUKSET",
        "language": "Kieli",
        "master_volume": "Kokonaisäänenvoimakkuus",
        "music_volume": "Taustaääni",
        "effects_volume": "Tehosteet",
        "comment_audio": "Kommenttiäänet",
        "subtitles": "Tekstitykset",
        "driver": "Kuski",
        "overpass_endpoints": "Overpass-palvelimet",
        "physics_mode": "Ajofysiikka",
        "reset_configs": "Palauta oletusasetukset",
        "arcade": "Arcade",
        "simulation": "Simulaatio",
        "city_list": "Kaupunkilista",
        "city_editor_hint": "Klikkaa kaupunkia, kirjoita ja valitse ehdotus | ESC takaisin",
        "city_editor_search": "Uusi kaupunki",
        "settings_hint": "UP/DOWN valitsee | LEFT/RIGHT säätää | ENTER vahvistaa | ESC takaisin",
        "paused": "PELI TAUOLLA",
        "continue": "Jatka peliä",
        "help": "Tutoriaali",
        "tutorial": "TUTORIAALI",
        "settings_menu": "Asetukset",
        "change_city": "Vaihda kaupunkia",
        "main_menu": "Alkuvalikko",
        "exit": "Lopeta peli",
        "help_close": "Esc / F1: sulje tutoriaali",
        "phone": "Puhelin: tarjoukset",
        "select_ride": "Valitse kyyti puhelimessa",
        "rage": "Rattiraivo",
        "respawn": "Respawn",
        "cancel_ride": "Hylkää kyyti",
        "reset_trip": "Nollaa matkamittari",
        "refuel": "Tankkaa polttoaineasemalla",
        "labels": "Nimet päälle / pois",
        "lane_assist": "Kaista-avustin",
        "speed_limiter": "Nopeusrajoitin",
        "red_assist": "Liikennevaloavustin",
        "zoom": "Zoomaus",
        "compass": "Kompassi",
        "pause": "Tauko",
        "help_short": "Avaa nämä ohjeet",
        "screenshot": "Tallenna kuvakaappaus",
        "on": "PÄÄLLÄ",
        "off": "POIS",
        "controls": "Ohjaus",
        "ways": "Tiet",
        "latitude": "Lat",
        "longitude": "Lon",
        "client": "asiakas",
        "points": "pistettä",
        "loading_osm": "Ladataan OpenStreetMap-teitä ja maisemaa...",
        "ready": "Valmis",
        "weather_forecast_24h": "Arvioitu sää seuraavalle 24 tunnille",
        "press_any_key_start": "Paina mitä tahansa aloittaaksesi",
        "weather_clear": "Selkeää",
        "weather_rain": "Sadetta",
        "weather_slush": "Räntää",
        "weather_snow": "Lumisadetta",
        "weather_thunderstorm": "Ukkosta",
        "select_mode": "Valitse pelimoodi",
        "career": "Ura",
        "gig_driver": "Keikkakuski",
        "reset_career": "Nollaa ura",
        "clear_cache": "Tyhjennä välimuisti kokonaan",
        "outdated_cache_title": "Välimuisti on päivitettävä",
        "outdated_cache_message": "Välimuisti täytyy tyhjentää versiopäivityksen yhteydessä. Tyhjennetäänkö välimuisti nyt?",
        "ok": "OK",
        "cancel": "Peruuta",
        "exit_car": "Poistu autosta / palaa autoon",
        "walk": "Kävele",
        "run": "Juokse",
        "career_city": "Uran kaupunki",
        "career_complete": "Ura suoritettu! Helsinki on valloitettu.",
        "city_summary": "Kaupungin yhteenveto",
        "city_summary_score": "Pisteet: {score}",
        "city_summary_fares": "Ajetut keikat: {fares}",
        "next_city": "Seuraava kaupunki: {city}",
        "continue_enter": "Paina Enter jatkaaksesi",
        "career_total_score": "Uran kokonaispisteet: {score}",
        "select_choose_resume": "Ylös/alas = valitse | Enter/Space = vahvista | Esc = jatka",
        "taxi_phone": "TAKSIPUHELIN",
        "pickup_short": "NOUTO",
        "dropoff_short": "PERILLE",
        "fare_pickup": "KYYTI: Nouda {name} paikasta {address}",
        "fare_dropoff": "KYYTI: Vie {name} määränpäähän {address}",
        "elapsed_time": "Kulunut aika",
        "estimated_distance": "Matkaa jäljellä",
        "fare_distance": "Ajettu matka",
        "speed_camera_hit": "Peltipoliisi! Ylinopeutta {excess} km/h -{penalty} pistettä",
        "police_stop": "Poliisipysäytys! -{penalty} pistettä",
        "crash": "Kolari! -{penalty} pistettä",
        "building_crash": "Törmäys rakennukseen! -{penalty} pistettä",
        "bridge_crash": "Törmäys sillan kaiteeseen! -{penalty} pistettä",
        "tree_crash": "Törmäys puuhun! -{penalty} pistettä",
        "fence_crash": "Törmäys aitaan! -{penalty} pistettä",
        "roadwork_blocked": "Tietöitä! Reitti on suljettu.",
        "water_driving": "Ajoit veteen! Palautetaan auto.",
        "water_timer": "Poistu vedestä",
        "red_light_violation": "Punaisen valon rikkomus! -{penalty} pistettä",
        "wrong_way_penalty": "Väärään suuntaan! -{penalty} pistettä",
        "pedestrian_way_penalty": "Ajat jalkakäytävällä! -{penalty} pistettä",
        "new_fare_at": "Uusi kyyti! Nouda {name} paikasta {address}",
        "slow_pickup_notice": "Hidasta noutaaksesi asiakkaan!",
        "slow_dropoff_notice": "Hidasta pysähtyäksesi määränpäähän!",
        "idea": "Pelin idea",
        "story": "Taustatarina",
        "drive": "Kiihdytä",
        "brake": "Jarruta / peruuta",
        "left": "Ohjaa vasemmalle",
        "right": "Ohjaa oikealle",
        "open_phone": "Avaa puhelin (P) ja valitse kyyti aloittaaksesi.",
        "finish_or_cancel": "Viimeistele tai peruuta nykyinen kyyti ensin",
        "no_requests": "Ei tarjouksia saatavilla",
        "pickup": "Nouto",
        "to": "Määränpää",
        "distance_client": "Matka asiakkaalle",
        "distance_trip": "Matka kohteeseen",
        "close_phone": "P / Esc: sulje",
        "reject_phone": "X: hylkää kyyti",
        "new_request": "Uusi kyyti odottaa puhelimessa.",
        "prebooked_taxi": "ENNAKKOTILAUS",
        "rail_booking_notice": "Ennakkotilaus: {train}, {station} {arrival}.",
        "rail_booking_accepted": "Ennakkotilaus hyväksytty: {train}, {station} {arrival}.",
        "booking_pending": "ODOTTAA", "booking_accepted": "HYVÄKSYTTY",
        "booking_train_arriving": "JUNA SAAPUU", "booking_passenger_waiting": "ASIAKAS ODOTTAA",
        "booking_passenger_met": "ASIAKAS TULOSSA",
        "rail_booking_met": "Ennakkotilaaja {name} ({train}) löytyi! Määränpää: {address}",
        "phone_available": "UUSI KYYTI! Avaa puhelin (P)",
        "stand_boarded": "{name} hyppäsi kyytiin! Määränpää: {address}",
        "hail_boarded": "{name} huusi taksin! Määränpää: {address}",
        "hail_walking": "{name} huusi taksin ja kävelee taksiin...",
        "walking": "kävelee taksiin...",
        "boarded": "nousi kyytiin! Määränpää",
        "fare_complete": "Kyyti valmis!",
        "road": "Tie", "off_road": "Maastossa", "limit": "Rajoitus",
        "trip": "Matka", "odometer": "Mittari", "trip_meter": "Trippimittari", "career_meter": "Matkamittari", "score": "PISTEET", "engine": "moottori",
        "fares": "Kyydit", "balance": "SALDO", "taxi_meter": "TAKSAMITTARI", "happiness": "TYYTYVÄISYYS", "speed": "NOPEUS", "rage_meter": "RATTIRAIVO", "next_train": "Seuraava juna", "train_car": "vaunu", "passengers_in_car": "matkustajaa", "car_profile_locomotive": "veturi", "car_profile_restaurant": "ravintolavaunu", "car_profile_family": "perhevaunu", "car_profile_pet": "lemmikkivaunu", "car_profile_standard": "matkustajavaunu", "drunk": "humalassa", "no_passengers": "ei matkustajia", "next_trains": "Saapuvat", "departing_trains": "Lähtevät", "timetable_available": "Juna-aikataulut saatavilla. Paina J.", "back_to_taxi": "Takaisin taksiin (ESC)", "track": "raide", "fuel": "POLTTOAINE", "fuel_economy": "KULUTUS", "fuel_station": "G: TANKKAA", "fuel_empty": "Polttoaine loppui! Respawnaa auto painamalla R.", "fuel_no_station": "Aja lähemmäs polttoainepumppua.", "fuel_enter_car": "Mene taksiin ennen tankkausta.", "hint_enter_taxi": "Painamalla F pääset sisään taksiisi", "hint_greet_passenger": "F: tervehdi asiakasta", "historical_weather": "Historiallinen sää (FMI)", "weather_source_observed": "havainto", "weather_source_forecast": "ennuste", "weather_source_generated": "arvio", "hint_start_engine": "Käynnistä moottori painamalla E", "fuel_stop_car": "Pysäytä taksi ennen tankkausta.", "fuel_tank_full": "Polttoainetankki on jo täynnä.", "fuel_no_money": "Ei rahaa polttoaineeseen.", "fuel_purchased": "Tankattu {liters:.1f} l, maksoi {cost:.2f} €.",
        "passenger_nausea_warning": "Asiakkaalla on huono olo! Pysähdy nopeasti!",
        "passenger_smells_intoxicated": "Asiakas haisee alkoholilta.",
        "passenger_nausea_bubble": "Oksettaa!",
        "passenger_nausea_relieved": "Asiakkaalle tuli parempi olo. Kyyti jatkuu.",
        "passenger_vomited": "Asiakas oksensi autoon! -{penalty} pistettä. Pysähdy.",
        "passenger_vomited_outside": "Asiakas oksensi ulos.",
        "walking_named": "{name} kävelee taksiin...",
        "boarded_destination": "{name} nousi kyytiin! Määränpää: {address}",
        "fare_complete_points": "Kyyti valmis! Hinta {amount}, tippi {tip}, +{earned} pistettä ({avg:.0f} km/h keskiarvo, {seconds:.1f} s)",
    },
    "en": {
        "select_language": "Select language",
        "language_hint": "LEFT/RIGHT or number key, ENTER / SPACE confirms",
        "select_city": "Select starting city (3x3 km OSM map)",
        "city_hint": "ARROWS or 1-0/A-D/G-Z select, E edits, F refreshes map, ENTER / SPACE starts, ESC quits",
        "refresh_map": "Fetch latest map",
        "edit_city_list": "Edit city list",
        "settings": "SETTINGS",
        "language": "Language",
        "master_volume": "Master volume",
        "music_volume": "Background sound",
        "effects_volume": "Sound effects",
        "comment_audio": "Comment audio",
        "subtitles": "Subtitles",
        "driver": "Driver",
        "overpass_endpoints": "Overpass endpoints",
        "physics_mode": "Driving physics",
        "reset_configs": "Reset settings",
        "arcade": "Arcade",
        "simulation": "Simulation",
        "city_list": "City list",
        "city_editor_hint": "Click a city, type a name, then choose a suggestion | ESC back",
        "city_editor_search": "New city",
        "settings_hint": "UP/DOWN selects | LEFT/RIGHT adjusts | ENTER activates | ESC back",
        "paused": "GAME PAUSED",
        "continue": "Continue Game",
        "help": "Tutorial",
        "tutorial": "TUTORIAL",
        "settings_menu": "Settings",
        "change_city": "Change City",
        "main_menu": "Main Menu",
        "exit": "Exit Game",
        "help_close": "Esc / F1: close tutorial",
        "phone": "Phone: ride offers",
        "select_ride": "Select a ride in the phone",
        "rage": "Road Rage",
        "respawn": "Respawn",
        "cancel_ride": "Cancel fare",
        "reset_trip": "Reset trip meter",
        "refuel": "Refuel at fuel station",
        "labels": "Toggle labels",
        "lane_assist": "Lane assist",
        "speed_limiter": "Speed limiter",
        "red_assist": "Traffic light assist",
        "zoom": "Zoom",
        "compass": "Compass",
        "pause": "Pause",
        "help_short": "Open these instructions",
        "screenshot": "Save screenshot",
        "on": "ON",
        "off": "OFF",
        "controls": "Controls",
        "ways": "Ways",
        "latitude": "Lat",
        "longitude": "Lon",
        "client": "client",
        "points": "pts",
        "loading_osm": "Loading OpenStreetMap roads & scenery...",
        "ready": "Ready",
        "weather_forecast_24h": "Approximate weather for the next 24 hours",
        "press_any_key_start": "Press any key to start",
        "weather_clear": "Clear",
        "weather_rain": "Rain",
        "weather_slush": "Slush",
        "weather_snow": "Snow",
        "weather_thunderstorm": "Thunderstorm",
        "select_mode": "Select game mode",
        "career": "Career",
        "gig_driver": "Gig Driver",
        "reset_career": "Reset career",
        "clear_cache": "Clear all map cache",
        "outdated_cache_title": "Cache update required",
        "outdated_cache_message": "The cache must be cleared after a version update. Clear the cache now?",
        "ok": "OK",
        "cancel": "Cancel",
        "exit_car": "Exit / enter taxi",
        "walk": "Walk",
        "run": "Run",
        "career_city": "Career city",
        "career_complete": "Career complete! Helsinki conquered.",
        "city_summary": "City summary",
        "city_summary_score": "Score: {score}",
        "city_summary_fares": "Fares completed: {fares}",
        "next_city": "Next city: {city}",
        "continue_enter": "Press Enter to continue",
        "career_total_score": "Total career score: {score}",
        "select_choose_resume": "UP/DOWN = select | ENTER/SPACE = choose | ESC = resume",
        "taxi_phone": "TAXI PHONE",
        "pickup_short": "PICKUP",
        "dropoff_short": "DROPOFF",
        "fare_pickup": "FARE: Pick up {name} at {address}",
        "fare_dropoff": "FARE: Take {name} to {address}",
        "elapsed_time": "Elapsed time",
        "estimated_distance": "Distance left",
        "fare_distance": "Fare distance",
        "speed_camera_hit": "Speed camera! {excess} km/h over -{penalty} pts",
        "police_stop": "Police stop! -{penalty} pts",
        "crash": "Crash! -{penalty} pts",
        "building_crash": "Building crash! -{penalty} pts",
        "bridge_crash": "Bridge guardrail crash! -{penalty} pts",
        "tree_crash": "Tree crash! -{penalty} pts",
        "fence_crash": "Fence crash! -{penalty} pts",
        "roadwork_blocked": "Roadworks! Route blocked.",
        "water_driving": "You drove into the water! Respawning.",
        "water_timer": "Leave the water",
        "red_light_violation": "Red Light Violation! -{penalty} pts",
        "wrong_way_penalty": "Wrong Way Penalty! -{penalty} pts",
        "pedestrian_way_penalty": "Driving on a pedestrian way! -{penalty} pts",
        "new_fare_at": "New fare! Pick up {name} at {address}",
        "slow_pickup_notice": "Slow down to pick up passenger!",
        "slow_dropoff_notice": "Slow down at destination to drop off!",
        "idea": "Game objective",
        "story": "Background story",
        "drive": "Accelerate",
        "brake": "Brake / reverse",
        "left": "Steer left",
        "right": "Steer right",
        "open_phone": "Press P to open the phone and choose a ride.",
        "finish_or_cancel": "Finish or cancel the current fare first",
        "no_requests": "No requests available",
        "pickup": "Pickup",
        "to": "Destination",
        "distance_client": "Distance to client",
        "distance_trip": "Trip distance",
        "close_phone": "P / Esc: close",
        "reject_phone": "X: reject ride",
        "new_request": "A new ride is waiting in the phone.",
        "prebooked_taxi": "PRE-BOOKED TAXI",
        "rail_booking_notice": "Pre-booked taxi: {train}, {station} {arrival}.",
        "rail_booking_accepted": "Pre-booking accepted: {train}, {station} {arrival}.",
        "booking_pending": "PENDING", "booking_accepted": "ACCEPTED",
        "booking_train_arriving": "TRAIN ARRIVING", "booking_passenger_waiting": "PASSENGER WAITING",
        "booking_passenger_met": "PASSENGER COMING",
        "rail_booking_met": "Pre-booked customer {name} ({train}) found! Destination: {address}",
        "phone_available": "NEW RIDE! Open phone (P)",
        "stand_boarded": "{name} jumped in! Destination: {address}",
        "hail_boarded": "{name} hailed your taxi! Destination: {address}",
        "hail_walking": "{name} hailed your taxi and is walking over...",
        "walking": "is walking to the taxi...",
        "boarded": "boarded! Destination",
        "fare_complete": "Fare complete!",
        "road": "Road", "off_road": "Off-road", "limit": "Limit",
        "trip": "Trip", "odometer": "Odo", "trip_meter": "Trip meter", "career_meter": "Odometer", "score": "SCORE", "engine": "engine",
        "fares": "Fares", "balance": "BALANCE", "taxi_meter": "FARE METER", "happiness": "HAPPINESS", "speed": "SPEED", "rage_meter": "ROAD RAGE", "next_train": "Next train", "train_car": "car", "passengers_in_car": "passengers", "car_profile_locomotive": "locomotive", "car_profile_restaurant": "restaurant car", "car_profile_family": "family car", "car_profile_pet": "pet car", "car_profile_standard": "passenger car", "drunk": "drunk", "no_passengers": "no passengers", "next_trains": "Arrivals", "departing_trains": "Departures", "timetable_available": "Train timetables available. Press J.", "back_to_taxi": "Back to taxi (ESC)", "track": "track", "fuel": "FUEL", "fuel_economy": "CONSUMPTION", "fuel_station": "G: REFUEL", "fuel_empty": "Out of fuel! Press R to respawn the car.", "fuel_no_station": "Drive closer to a fuel pump.", "fuel_enter_car": "Enter the taxi before refueling.", "hint_enter_taxi": "Press F to get into your taxi", "hint_greet_passenger": "F: greet passenger", "historical_weather": "Historical weather (FMI)", "weather_source_observed": "observed", "weather_source_forecast": "forecast", "weather_source_generated": "estimate", "hint_start_engine": "Press E to start the engine", "fuel_stop_car": "Stop the taxi before refueling.", "fuel_tank_full": "The fuel tank is already full.", "fuel_no_money": "Not enough money for fuel.", "fuel_purchased": "Refueled {liters:.1f} L for €{cost:.2f}.",
        "passenger_nausea_warning": "The passenger feels sick! Stop quickly!",
        "passenger_smells_intoxicated": "The passenger smells intoxicated.",
        "passenger_nausea_bubble": "I feel sick!",
        "passenger_nausea_relieved": "The passenger feels better. Continue the fare.",
        "passenger_vomited": "The passenger vomited in the taxi! -{penalty} points. Stop.",
        "passenger_vomited_outside": "The passenger vomited outside.",
        "walking_named": "{name} is walking to the taxi...",
        "boarded_destination": "{name} boarded! Destination: {address}",
        "fare_complete_points": "Fare complete! Fare {amount}, tip {tip}, +{earned} pts ({avg:.0f} km/h average in {seconds:.1f}s)",
    },
}


def normalize_language(language: str) -> str:
    return language if language in SUPPORTED_LANGUAGES else "fi"


def tr(language: str, key: str, **values: object) -> str:
    text = TRANSLATIONS[normalize_language(language)].get(key, key)
    return text.format(**values) if values else text
