"""Small built-in Finnish and English translation table."""

SUPPORTED_LANGUAGES = ("fi", "en")
LANGUAGE_NAMES = {"fi": "Suomi", "en": "English"}

TRANSLATIONS = {
    "fi": {
        "select_language": "Valitse kieli",
        "language_hint": "Vasen/Oikea tai numeronäppäin, ENTER / SPACE vahvistaa",
        "select_city": "Valitse aloituskaupunki (4x4 km OSM-kartta)",
        "city_hint": "UP/DOWN/LEFT/RIGHT tai 1-0, ENTER / SPACE aloittaa, ESC lopettaa",
        "settings": "ASETUKSET",
        "language": "Kieli",
        "master_volume": "Kokonaisäänenvoimakkuus",
        "music_volume": "Taustaääni",
        "effects_volume": "Tehosteet",
        "settings_hint": "UP/DOWN valitsee | LEFT/RIGHT säätää | ENTER vaihtaa kieltä | ESC takaisin",
        "paused": "PELI TAUKOLLA",
        "continue": "Jatka peliä",
        "help": "Ohjeet ja pelin idea",
        "settings_menu": "Asetukset",
        "change_city": "Vaihda kaupunkia",
        "exit": "Lopeta peli",
        "help_close": "Esc / F1: sulje",
        "phone": "Puhelin: tarjoukset",
        "select_ride": "Valitse kyyti puhelimessa",
        "rage": "Raivohuuto",
        "respawn": "Respawn",
        "cancel_ride": "Hylkää kyyti",
        "reset_trip": "Nollaa matkamittari",
        "labels": "Nimet päälle / pois",
        "lane_assist": "Kaista-avustin",
        "speed_limiter": "Nopeusrajoitin",
        "red_assist": "Liikennevaloavustin",
        "zoom": "Zoomaus",
        "pause": "Tauko",
        "help_short": "Avaa nämä ohjeet",
        "idea": "Pelin idea",
        "story": "Taustatarina",
        "drive": "Kiihdytä",
        "brake": "Jarruta / peruuta",
        "left": "Ohjaa vasemmalle",
        "right": "Ohjaa oikealle",
        "open_phone": "Avaa puhelin (P) ja valitse kyyti aloittaaksesi.",
        "finish_or_cancel": "Viimeistele tai peruuta nykyinen kyyti ensin",
        "no_requests": "Ei tarjouksia saatavilla",
        "pickup": "Nouto",
        "to": "Määränpää",
        "distance_client": "Matka asiakkaalle",
        "close_phone": "P / Esc: sulje",
        "reject_phone": "X: hylkää kyyti",
        "new_request": "Uusi kyyti odottaa puhelimessa.",
        "phone_available": "UUSI KYYTI! Avaa puhelin (P)",
        "stand_boarded": "{name} hyppäsi kyytiin! Määränpää: {address}",
        "hail_boarded": "{name} huusi taksin! Määränpää: {address}",
        "slow_pickup": "Hidasta noutaaksesi asiakkaan!",
        "walking": "kävelee taksiin...",
        "boarded": "nousi kyytiin! Määränpää",
        "slow_dropoff": "Hidasta pysähtyäksesi määränpäähän!",
        "fare_complete": "Kyyti valmis!",
        "road": "Tie", "off_road": "Maastossa", "limit": "Rajoitus",
        "trip": "Matka", "odometer": "Mittari", "score": "PISTEET",
        "fares": "Kyydit", "speed": "NOPEUS", "rage_meter": "RAIVO",
        "walking_named": "{name} kävelee taksiin...",
        "boarded_destination": "{name} nousi kyytiin! Määränpää: {address}",
        "fare_complete_points": "Kyyti valmis! +{earned} pistettä ({avg:.0f} km/h keskiarvo, {seconds:.1f} s)",
    },
    "en": {
        "select_language": "Select language",
        "language_hint": "LEFT/RIGHT or number key, ENTER / SPACE confirms",
        "select_city": "Select starting city (4x4 km OSM map)",
        "city_hint": "UP/DOWN/LEFT/RIGHT or 1-0, ENTER / SPACE starts, ESC quits",
        "settings": "SETTINGS",
        "language": "Language",
        "master_volume": "Master volume",
        "music_volume": "Background sound",
        "effects_volume": "Sound effects",
        "settings_hint": "UP/DOWN selects | LEFT/RIGHT adjusts | ENTER changes language | ESC back",
        "paused": "GAME PAUSED",
        "continue": "Continue Game",
        "help": "Controls & Objective",
        "settings_menu": "Settings",
        "change_city": "Change City",
        "exit": "Exit Game",
        "help_close": "Esc / F1: close",
        "phone": "Phone: ride offers",
        "select_ride": "Select a ride in the phone",
        "rage": "Rage shout",
        "respawn": "Respawn",
        "cancel_ride": "Cancel fare",
        "reset_trip": "Reset trip meter",
        "labels": "Toggle labels",
        "lane_assist": "Lane assist",
        "speed_limiter": "Speed limiter",
        "red_assist": "Traffic light assist",
        "zoom": "Zoom",
        "pause": "Pause",
        "help_short": "Open these instructions",
        "idea": "Game objective",
        "story": "Background story",
        "drive": "Accelerate",
        "brake": "Brake / reverse",
        "left": "Steer left",
        "right": "Steer right",
        "open_phone": "Press P to open the phone and choose a ride.",
        "finish_or_cancel": "Finish or cancel the current fare first",
        "no_requests": "No requests available",
        "pickup": "Pickup",
        "to": "Destination",
        "distance_client": "Distance to client",
        "close_phone": "P / Esc: close",
        "reject_phone": "X: reject ride",
        "new_request": "A new ride is waiting in the phone.",
        "phone_available": "NEW RIDE! Open phone (P)",
        "stand_boarded": "{name} jumped in! Destination: {address}",
        "hail_boarded": "{name} hailed your taxi! Destination: {address}",
        "slow_pickup": "Slow down to pick up passenger!",
        "walking": "is walking to the taxi...",
        "boarded": "boarded! Destination",
        "slow_dropoff": "Slow down at destination to drop off!",
        "fare_complete": "Fare complete!",
        "road": "Road", "off_road": "Off-road", "limit": "Limit",
        "trip": "Trip", "odometer": "Odo", "score": "SCORE",
        "fares": "Fares", "speed": "SPEED", "rage_meter": "RAGE",
        "walking_named": "{name} is walking to the taxi...",
        "boarded_destination": "{name} boarded! Destination: {address}",
        "fare_complete_points": "Fare complete! +{earned} pts ({avg:.0f} km/h average in {seconds:.1f}s)",
    },
}


def normalize_language(language: str) -> str:
    return language if language in SUPPORTED_LANGUAGES else "fi"


def tr(language: str, key: str, **values: object) -> str:
    text = TRANSLATIONS[normalize_language(language)].get(key, key)
    return text.format(**values) if values else text
